import { Metadata } from "next";
import { JSX } from "react";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Test-Task",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang="ru">
      <TimeProvider>
        <Header />
        <body className={`${montserrat.className} body`}>{children}</body>
      </TimeProvider>
    </html>
  );
};

export default RootLayout;
