import { Metadata } from "next";
import { JSX } from "react";
import "./globals.css";

import { Montserrat } from "next/font/google";
import { Header } from "./components/Header/Header";
import TimeProvider from "./services/TimeContext";
const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
});

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Test-Task",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang="ru">
      <TimeProvider>
        <Header />
        <body className={`${montserrat.className} body`}>{children}</body>
      </TimeProvider>
    </html>
  );
};

export default RootLayout;
